name: angular2_components_test
version: 0.0.1
description: Angular2 Components Test
publish_to: none

environment:
  sdk: ">=1.22.1 <2.0.0"
dependencies:
  angular2: ^3.0.0-alpha
  angular2_components: ^0.4.0-alpha
  http: ^0.11.3+9
dev_dependencies:
  angular_test: ^1.0.0-alpha+6
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  grinder: ^0.8.0+2
  mockito: ^2.0.2
  pageloader: ^2.2.5
  test: ^0.12.20+3
transformers:
- angular2/transform/codegen:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
- angular2/transform/reflection_remover:
    $include:
      - test/components/**_test.dart
      - web/main.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
